services:
  ecommerceapi:
    build:
      context: ./ECommerceApi
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"

      Jwt__Key: "ECommerceApi-Development-Key-2026-Guclu-Ve-Uzun-Secret"
      Jwt__Issuer: "ECommerceApi"
      Jwt__Audience: "ECommerceApiUser"
      Jwt__AccessTokenExpirationMinutes: "15"
      Jwt__RefreshTokenExpirationDays: "7"

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: